#ifndef __LAUDIO_PORT_DEFS_H__
#define __LAUDIO_PORT_DEFS_H__

#define LAUDIO_PORT_ACP_4_AS (7789)
#define LAUDIO_PORT_PD_4_ACP (7790)
#define LAUDIO_PORT_PD_4_RENDER (7791)
#define LAUDIO_PORT_PD_4_CAPTURE (7792)



#endif //__LAUDIO_PORT_DEFS_H__